### ISSUE TITLE
Laravel Cashier upgrade rules

### ISSUE THREAD

**Issue by GeniJaho** [driftingly/rector-laravel#100]
Can we include rules to upgrade Cashier to later versions like 13 and 14 in this repository? At least to handle the boring method renames and whatever work that can be automated.

Since it's a first-party Laravel package it would make sense to include it in this repo, but while adding new classes that are Cashier-specific, the Rector rules become bloated and hard to navigate.

A solution could be to prepend the rules with the Cashier prefix, for example, `CashierStripeOptionsToStripeRector`. 

Or would a new repository be a better idea?

**Comment by driftingly** [comment]
Closed by #103
