### ISSUE TITLE
Support for rector 1.0.0

### ISSUE THREAD

**Issue by dominik-eller** [driftingly/rector-laravel#177]
It seems there is actually no support for the latest rector release (1.0.0).

I am getting some errors.

First the rector.php config structure changed and ->sets() seems to be replaced by ->withSets().

Changing that brings up an error:

 [ERROR] Class "Rector\Core\Rector\AbstractRector" not found.

**Comment by driftingly** [comment]
As part of the update to Rector `0.19` https://github.com/rectorphp/rector/releases/tag/0.19.0
We updated references to `Rector\Core\`

```diff
-use Rector\Core\
+use Rector\
```

So if you're coming from a previous version you may need to update your code. 
I have a [PR pending](https://github.com/driftingly/rector-laravel/pulls) for the `1.0` update.
I'll need to double check the `sets` issue.

**Comment by driftingly** [comment]
Just tagged `1.0.0` with updated documentation to include the `withSets` changes. 
Thanks for the heads up!
