### ISSUE TITLE
Do we use a fixed Linter configuration or go with the latest updates?

### ISSUE THREAD

**Issue by GeniJaho** [driftingly/rector-laravel#228]
Hi @driftingly @peterfox,
The current PRs are failing the build because of the latest Duster/CSFixer/Pint updates, not sure which ones.
The Pint run fails because of the rule `single_line_empty_body`.
I can add a `pint.json` file and skip it there, and it would solve the issue, but do we want to do that?
The alternative is to run the duster on the whole project, take the latest defaults, and continue doing that in the future.
I have no preference on using the `single_line_empty_body` rule or not, either way is fine IMO.

For now, I'm adding a `pint.json` config to keep the existing styling.

**Comment by peterfox** [comment]
I've only just seen this @GeniJaho 😓 my bad. I think adding the `pint.json` file made sense. Always happy to review though and add new rules.
