### ISSUE TITLE
Lack of available sets in 1.2.0 release

### ISSUE THREAD

**Issue by mtracz** [driftingly/rector-laravel#235]
I noticed that:
- 1.2.0 release has been released 3 May
- readme has been updated 7 May with 2 new sets (`LARAVEL_CONTAINER_STRING_TO_FULLY_QUALIFIED_NAME`, `LARAVEL_IF_HELPERS`)
  - https://github.com/driftingly/rector-laravel/commit/ea914dce1a04143fcc4d3e8b70be47db59247910
- readme has been updated 2 Jun with new set `LARAVEL_ARRAYACCESS_TO_METHOD_CALL`
  - https://github.com/driftingly/rector-laravel/commit/50dd0cf9161d6b27c13030aac4505ff744a2417f
  
Actually these 3 sets above are not available in 1.2.0 release and users cannot use them as described in the readme.

I think new release should be released to match readme and allow to use all described features.

**Comment by GeniJaho** [comment]
@driftingly Draft [release](https://github.com/driftingly/rector-laravel/releases/tag/untagged-7bc808de91db3dffea3a) ready. 😁 🚀

**Comment by giagara** [comment]
+1 for this

**Comment by GeniJaho** [comment]
New sets available in https://github.com/driftingly/rector-laravel/releases/tag/1.2.1.
