### ISSUE TITLE
Missing fix for SelfHandling?

### ISSUE THREAD

**Issue by sambenskin** [driftingly/rector-laravel#254]
The SelfHandling interface was deprecated in Laravel 5.2 and removed in 5.3, but when I run either LaravelSetList::LARAVEL_52 or LaravelSetList::LARAVEL_53 It's not affecting any of the files where we have code like
```
class SomeJob extends Job implements SelfHandling
```

My understanding is that this just needs removing so it should correct this line to
```
class SomeJob extends Job
```

Or have I missed something?

**Comment by GeniJaho** [comment]
@sambenskin can you find a link to a PR/commit in the framework where it was removed please?
If we add a rule for it, we would have to add the link in the a comment.
Also, before you implement a custom rule for it, there might be an existing configurable rule to remove an interface, in the base Rector repository 😃

**Comment by sambenskin** [comment]
Thank you for fixing this.
