### ISSUE TITLE
AddGenericReturnTypeToRelationsRector not compliant with updated relation generic

### ISSUE THREAD

**Issue by joostdebruijn** [driftingly/rector-laravel#259]
In both Laravel (https://github.com/laravel/framework/pull/51851) as Larastan (https://github.com/larastan/larastan/pull/1990), the relation generics have been updated. Running the AddGenericReturnTypeToRelationsRector doesn't add the generic return types correctly anymore and even suggests to remove the correct ones. For example:

```diff
     /**
-     * @return \Illuminate\Database\Eloquent\Relations\HasMany<\App\Models\Post, $this>
+     * @return \Illuminate\Database\Eloquent\Relations\HasMany<\App\Models\Post>
      */
     public function posts(): HasMany
     {
          //
     }
```
I had a look at the implementation of the Rector rule but as of now I'm not confident enough how to fix the rule in the right way.

**Comment by canvural** [comment]
oh, I'm actually working on this. If someone else does not beat me to it, I'll create a PR.
