### ISSUE TITLE
Incoming PHPStan 2.0

### ISSUE THREAD

**Issue by MrYamous** [driftingly/rector-laravel#270]
Spotted from main Rector project, PHPStan will upgrade to 2.0 and some changes may be necessary here too

Upgrade process is still ongoing on main Rector but I thought it would be useful to at least start talking about it here

See related [Rector Issue](https://github.com/rectorphp/rector/issues/8815) and [PHPStan Discussion](https://github.com/phpstan/phpstan/discussions/11816)

**Comment by GeniJaho** [comment]
Thanks for opening the issue, I'm working on this, only 61 PHPStan issues 😄

**Comment by MrYamous** [comment]
Amazing timing, PHPStan 2 just released : https://phpstan.org/blog/phpstan-2-0-released-level-10-elephpants

**Comment by GeniJaho** [comment]
Fixed in https://github.com/driftingly/rector-laravel/pull/277.
