### ISSUE TITLE
Requirement for PHP 8.1

### ISSUE THREAD

**Issue by u01jmg3** [driftingly/rector-laravel#69]
Just wondering why this dependency requires a greater version of PHP (`>=8.1`) than Rector (`^7.2|^8.0`) does? It makes it more problematic to use on older versions of PHP. Thanks

**Comment by driftingly** [comment]
Note for me: This will help: https://github.com/symplify/config-transformer/blob/main/.github/workflows/downgraded_release.yaml

**Comment by driftingly** [comment]
Hey @u01jmg3, sorry for the delay on this.  I just released 0.16.1 which has been downgraded to support more PHP versions.

CC @marcelcunha
