### ISSUE TITLE
Rector 0.15.0 - Laravel60|70 - ParamTypeDeclarationRector throws error

### ISSUE THREAD

**Issue by sidneyprins** [driftingly/rector-laravel#72]
Hey,

Using:
- Rector 0.15.0
- Rector-Laravel 0.14.1

I use the set 
- LaravelLevelSetList::UP_TO_LARAVEL_90,

When running rector, I get the following error:
- [ERROR] Use specific rules to infer params instead. This rule was split info many small ones.

Seems to refer to the following file in rector-laravel:
- https://github.com/driftingly/rector-laravel/blob/main/config/sets/laravel60.php#L26
- This one might also break: https://github.com/driftingly/rector-laravel/blob/main/config/sets/laravel70.php#L21-L47

I did some small digging, looks like 0.15.0 of rector now throws an error.
- https://github.com/rectorphp/rector/blob/0.15.0/rules/TypeDeclaration/Rector/FunctionLike/ParamTypeDeclarationRector.php#L65

Current solution is to use older version of rector, but thought I'd report this.

**Comment by alexhampu** [comment]
@joelvh you can skip only the rule, instead of the whole set:

![image](https://user-images.githubusercontent.com/21214654/215604007-27a03255-ef4d-4bb3-965b-1612e439f6ef.png)

**Comment by joelvh** [comment]
Very nice, thanks @alexhampu!

**Comment by sidneyprins** [comment]
Note, downgrading Rector to 0.14.x is also a solution, that way you don't have to exclude a set or rule. That's what I've chosen to do until there's a fix

**Comment by driftingly** [comment]
This should be fixed by #91
