### ISSUE TITLE
Relations return type rector is incomplete

### ISSUE THREAD

**Issue by chris-ware** [driftingly/rector-laravel#79]
When utilising the `AddGenericReturnTypeToRelationsRector` rector, some of the relations it generates are incomplete. In my case, this mostly affects belongs to, where Larastan is expecting <RelatedModel, CurrentModel> but is only recieving <RelatedModel>. I have a feeling quite a few of the relationships have this expectation.

**Comment by driftingly** [comment]
Closing for now, feel free to reopen if this is still an issue.
