### ISSUE TITLE
Call to undefined method Rector\Core\NodeManipulator\ClassMethodManipulator::addMethodParameterIfMissing()

### ISSUE THREAD

**Issue by alexey-m-ukolov** [driftingly/rector-laravel#90]
Method is called [here](https://github.com/driftingly/rector-laravel/blame/7aae907cb280ff4c06dd7efa33c558df43eafa03/src/Rector/StaticCall/RequestStaticValidateToInjectRector.php#L91), but it was removed from rector in https://github.com/rectorphp/rector-src/pull/3245 and was tagged in [0.15.2](https://github.com/rectorphp/rector/releases/tag/0.15.2).

The easiest fix for now would be to set upper limit on required version in composer.json, I suppose.

**Comment by driftingly** [comment]
Resolved by #91
